[platformio]
default_envs = squixl

[env]

; Required ESP32 Arduino Core version for SQUiXL
; 3.1.1
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip

; This project is unable to be moved to a later ESP32 Arduino Core version than 3.1.1 at this stage too to changes in the IDF and the way the RGB Peripheral is handled, causing screen flickering due to flash/psram contention.
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.35/platform-espressif32.zip ; 3.3.5


; board = um_squixl // Not available before 3.2.0
board = um_nanos3
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = squixl_partitions_new.csv
board_upload.wait_for_upload_port = false ; Waiting isn't needed for CDC/JTAG USB 

; upload_protocol = espota
; upload_port = squixl.local  ;192.168.1.228

monitor_filters = esp32_exception_decoder

lib_deps =
	adafruit/Adafruit DRV2605 Library@1.2.4
	https://github.com/bitbank2/PNGdec.git
	https://github.com/bitbank2/JPEGdec.git

	earlephilhower/ESP8266Audio@2.0.0
	sparkfun/SparkFun MAX1704x Fuel Gauge Arduino Library
	knolleary/PubSubClient@^2.8

    esp32async/AsyncTCP@3.4.9
    esp32async/ESPAsyncWebServer@3.9.3

build_flags =
	-fexceptions
	-D ARDUINO_USB_MODE=1 ; CDC/JTAG USB mode
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_ARCH_ESP32=1
	-D BOARD_HAS_PSRAM
    -Os
    ; PNGdec buffer size for 480-wide 32-bpp PNGs: (480*4+1)*2 = 3842
    -D PNG_MAX_BUFFERED_PIXELS=3842
	; -D CORE_DEBUG_LEVEL=5
	; -D DISABLE_ALL_LIBRARY_WARNINGS
    -Wl,--allow-multiple-definition

build_unflags =
    -O2

[env:squixl]
build_flags =
	${env.build_flags}
	-D CORE_DEBUG_LEVEL=1 ; Log arduino core errors

; Push over WiFi once squixl has already been flashed once via USB.
; Usage: pio run -e squixl-ota -t upload
[env:squixl-ota]
build_flags = ${env:squixl.build_flags}
upload_protocol = espota
upload_port = SQUiXL.local